### ISSUE TITLE
手机号码格式判断逻辑似乎不对

### ISSUE THREAD

**Issue by HamiltonHuaji** [kurodaakira-jp/cloud-music#1]
我的电话号码是17X开头的, 这部分号码在https://cloudmusic.xyz/js/chunk-09f03926.4f3d63d2.js中会被判断为"手机号码格式错误", 因此无法登录. 
在"(13[0-9]|14[5|7]|15[0|1|2|3|5|6|7|8|9]|18[0|1|2|3|5|6|7|8|9])"这一句中加上17[0|1|2|3|5|6|7|8|9]即可.
谢谢!

**Comment by kurodaak1ra** [comment]
感谢反馈！已经加了

17段貌似是虚拟号段吧
