### ISSUE TITLE
嘿嘿嘿，我也是最求极致的复刻，不过我是用Android原生写的，老多图标他喵的找不到，贼难受

### ISSUE THREAD

**Issue by kalac2232** [kurodaakira-jp/cloud-music#2]
现在也就做了俩三个界面，写几天都懒得写了 过几天又想写了 反复这个状态

**Comment by kurodaak1ra** [comment]
下载安卓的apk，然后当压缩包打开，里面r文件夹下就有icon，不过我是照着png画的svg

**Comment by kalac2232** [comment]
我知道怎么获取Android 但是我是用Android 仿的ios界面，Android 不好看，然而ios与Android 页面还不太一样，图标也不太一样，有的图标根本找不到，现在也是想着自己画呢
